version: "3"

services:
  fashdb:
    image: "postgres:9.6-alpine"
    container_name: fashdb
    restart: always

    ports:
      - 5432:5432

    environment:
      - POSTGRES_DB=fashionhub
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata

  fashionhub:
    build: ./
    container_name: fashionhub
    environment:
      - DB_SERVER:fashdb
      - POSTGRES_DB=fashionhub
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 8550:8550
    depends_on:
      - fashdb

volumes:
  postgres_data:
